version: '3'
services:

  db:
    image: postgres:9.6
    container_name: ps-postgres
    hostname: db
    expose:
      - "5432"
    networks:
      jaz:
        aliases:
          - ps-postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ps-rabbitmq
    hostname: rabbitmq
    expose:
      - "5672"
      - "15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      jaz:
        aliases:
          - ps-rabbitmq

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ps-app
    hostname: app
    tty: true
    command: /site/docker-utils/start.sh
    volumes:
      - static-volume:/site/htdocs/static/
      - ./polyglot_source:/site/proj/polyglot_source
      - ./polyglot_data:/site/proj/polyglot_data
      - ./pgdb:/site/proj/pgdb
      - ./iscan_server:/site/proj/iscan_server
      - ./docker-utils:/site/docker-utils
      - ../PolyglotDB:/site/proj/PolyglotDB
      - ../ISCAN:/site/proj/ISCAN
      - ../SPADE:/site/proj/SPADE
      - ../unisyn_spade:/site/proj/unisyn_spade
    expose:
      - "80"
    ports:
      - 8080:8080
      - 80:80
      - 7400:7800
      - 8400:8800
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - SITE_DIR=/site/
      - PROJECT_NAME=iscan_server
      - DJANGO_DEBUG=True
    depends_on:
      - rabbitmq
      - db
      - worker
    networks:
      jaz:
        aliases:
          - ps-app

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ps-worker
    hostname: worker
    command: /site/env/bin/celery worker -A iscan_server --workdir /site/proj/ -l info
    ports:
      - 7402:7402
    volumes:
      - static-volume:/site/htdocs/static/
      - ./polyglot_source:/site/proj/polyglot_source
      - ./polyglot_data:/site/proj/polyglot_data
      - ./pgdb:/site/proj/pgdb
      - ./iscan_server:/site/proj/iscan_server
      - ./docker-utils:/site/docker-utils
      - ../PolyglotDB:/site/proj/PolyglotDB
      - ../ISCAN:/site/proj/ISCAN
      - ../SPADE:/site/proj/SPADE
      - ../unisyn_spade:/site/proj/unisyn_spade
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - SITE_DIR=/site/
      - PROJECT_NAME=iscan_server
      - DJANGO_DEBUG=False
    depends_on:
      - rabbitmq
    networks:
      jaz:
        aliases:
          - ps-worker

networks:
  jaz:

volumes:
  static-volume:
  polyglot_source:
    driver: "local"
  polyglot_data:
    driver: "local"
  pgdb:
    driver: "local"
  polyglot_server:
    driver: "local"
  docker-utils:
    driver: "local"
  PolyglotDB:
    driver: "local"
  test_data:
    driver: "local"
